### ISSUE TITLE
ValueError: Pandas data cast to numpy dtype of object when fitting OLS model

### ISSUE THREAD

**Issue by kev065** [learn-co-curriculum/dsc-interaction-terms-v2-5#1]
## Issue Subtype

- [X ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
import statsmodels.api as sm

# Prepare data for modeling
y = data["mpg"]
X_no_interaction = data[["cylinders", "weight"]].copy()
X_no_interaction = pd.get_dummies(X_no_interaction, columns=["cylinders"], drop_first=True)

# Build model and get results
no_interaction_model = sm.OLS(y, sm.add_constant(X_no_interaction))
no_interaction_results = no_interaction_model.fit()

# Plot the lines generated by the model for each selected category
plot_fit_lines(data, no_interaction_results, "cylinders", [4, 6, 8], [])
```

### Concern

The current implementation of the data preprocessing and model fitting code is causing a ValueError when trying to fit an OLS model using statsmodels. The error occurs because pandas is trying to cast categorical variables created using `pd.get_dummies()` to a numpy array, which can only contain one data type. 

This is the error message:  ValueError("Pandas data cast to numpy dtype of object. " 510 "Check input data with np.asarray(data).") 511 return super()._convert_endog_exog(endog, exog) ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).

## (Optional) Proposed Solution

```
import statsmodels.api as sm

# Prepare data for modeling
y = data["mpg"]
X_no_interaction = data[["cylinders", "weight"]].copy()

# Create dummy variables for the 'cylinders' column
X_no_interaction = pd.get_dummies(X_no_interaction, columns=["cylinders"], drop_first=True)

# Convert the dummy variables to numeric data type
X_no_interaction = X_no_interaction.astype(float)

# Build model and get results
no_interaction_model = sm.OLS(y, sm.add_constant(X_no_interaction))
no_interaction_results = no_interaction_model.fit()

# Plot the lines generated by the model for each selected category
plot_fit_lines(data, no_interaction_results, "cylinders", [4, 6, 8], [])
```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ X] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for bringing this to our attention. We'll take a look.

**Comment by bpurdy-ds** [comment]
That works. Cleaned that up and few other items. Will now update repo.
