### ISSUE TITLE
The linear regression formula in Section 1.4 seems to have an issue

### ISSUE THREAD

**Issue by setare92-ha** [learn-co-curriculum/dsc-interaction-terms-v2-5#2]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
In formula form, we are now saying:

$$ \large{ \text{mpg} = \beta_0 + \begin{cases}
  \beta_1 \times \text{weight} \times \beta_\text{interaction} + \beta_\text{(4 cylinders)} & \text{if 4 cylinders}, or\\
  \beta_1 \times \text{weight} + \beta_\text{(6 cylinders)} & \text{if 6 cylinders}, or\\
  \beta_1 \times \text{weight} + \beta_\text{(8 cylinders)} & \text{if 8 cylinders}.
\end{cases}} $$

Note that $\beta$s in this formula are not the same as in the previous formula. This is clear from the fact that the intercept for the 4 cylinders line $\beta_\text{(4 cylinders)}$ is higher in this graph than in the previous graph. Just like adding an additional independent variable to a multiple regression, adding an interaction fundamentally changes the model and the other coefficients will adjust accordingly.

```

### Concern

beta_1 and beta_interaction are being multiplied when they should be summed. The linear regression formula seems to be wrong. 

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for bringing this to our attention. We'll take a look.

**Comment by bpurdy-ds** [comment]
Correct. Since it is a slope it needs to be added to another slope, not multiplied by a slope.
